kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8s-sync-chart.name" . }}
  labels:
    {{- include "k8s-sync-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "nodes"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - extensions
  resourceNames:
  - {{ template "k8s-sync-chart.name" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
# k8s-sync creates cluster roles and bindings
- apiGroups:
  - ""
  resources:
  - "persistentvolumes"
  - "namespaces"
  - "persistentvolumeclaims"
  - "limitranges"
  - "resourcequotas"
  verbs:
  - "get"
  - "list"
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterroles"
  - "clusterrolebindings"
  - "roles"
  - "rolebindings"
  verbs:
  - "get"
  - "list"
  - "create"
- apiGroups:
  - "apps/v1"
  resources:
  - "deployments"
  - "replicasets"
  verbs:
  - "create"
  - "get"
  - "list"
  - "update"
  - "delete"
- apiGroups:
  - "policy"
  resources:
  - "podsecuritypolicies"
  verbs:
  - "get"
  - "list"
  - "create"
- apiGroups:
  - "policy"
  resources:
  - "podsecuritypolicies"
  resourceNames:
  - "student-nouid"
  - "student-perms"
  verbs:
  - "use"
