
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8s-sync-chart.name" . }}
  labels:
    {{- include "k8s-sync-chart.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "k8s-sync-chart.name" . }}
  apiGroup: ""
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "k8s-sync-chart.name" . }}
  apiGroup: ""
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8s-sync-chart.name" . }}-student-perms
  labels:
    {{- include "k8s-sync-chart.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "k8s-sync-chart.name" . }}
  apiGroup: ""
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.perms }}
  apiGroup: ""
