kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8s-sync-chart.name" . }}
  labels:
    {{- include "k8s-sync-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "nodes"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - extensions
  resourceNames:
  - {{ template "k8s-sync-chart.name" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
# k8s-sync creates cluster roles and bindings
- apiGroups:
  - ""
  resources:
  - "clusterroles"
  - "clusterrolebindings"
  - "persistentvolumes"
  verbs:
  - "get"
  - "list"
  - "create"
