kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8s-sync-chart.name" . }}
  labels: {{- include "k8s-sync-chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
      - "nodes"
    verbs:
      - "get"
      - "watch"
      - "list"
  # k8s-sync user creation
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
      - "nodes"
      - "role"
      - "rolebinding"
      - "clusterrolebinding"
      - "persistentvolume"
      - "persistentvolumeclaim"
      - "limitrange"
      - "resourcequota"
    verbs:
      - create
      - list
      - get
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - create
      - list
      - get
  # security
  - apiGroups:
      - extensions
    resourceNames:
      - {{ template "k8s-sync-chart.name" . }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
