kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8s-sync-chart.name" . }}
  labels: {{- include "k8s-sync-chart.labels" . | nindent 4 }}
rules:
  # k8s-sync user creation
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
      - "nodes"
      - "roles"
      - "rolebindings"
      - "clusterrolebindings"
      - "clusterroles"
      - "persistentvolumes"
      - "persistentvolumeclaims"
      - "limitranges"
      - "resourcequotas"
    verbs:
      - create
      - list
      - get
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - create
      - list
      - get
