apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  AWSED_CA: {{ .Values.AWSED_CA | b64enc | quote }}
  K8S_ENDPOINT: {{ .Values.K8S_ENDPOINT | b64enc | quote }}
  K8S_CA: {{ .Values.K8S_CA | b64enc | quote }}
  K8S_CERT: {{ .Values.K8S_CERT | b64enc | quote }}
  K8S_KEY: {{ .Values.K8S_KEY | b64enc | quote }}
  JAVA_OPTS: {{ default "" .Values.JAVA_OPTS | b64enc | quote }}
  AWSED_ENDPOINT: {{ .Values.AWSED_ENDPOINT | b64enc | quote }}
  AWSED_APIKEY: {{ .Values.AWSED_APIKEY | b64enc | quote }}
  SYNC_ENV: {{ .Values.SYNC_ENV | b64enc | quote }}
  SYNC_SCHEDULE: {{ .Values.SYNC_SCHEDULE | b64enc | quote }}
